platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'OpenClawRemote' do
  # Kotlin/Native frameworks would be linked here
  # pod 'shared', :path => '../shared'

  # Networking
  pod 'KtorClientDarwin', '~> 2.3.7'

  # Camera for QR scanning
  pod 'AVFoundation'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
